### PR TITLE
Upgrade sbt

### PR DESCRIPTION
**Pull request by mkurz**

### CODE REVIEW

**Comment by francisdb** [comment]
by the way, 1.3.3 should be out soon
https://github.com/sbt/sbt/releases/tag/v1.3.3

**Comment by mkurz** [comment]
Thanks for the hint.

**Comment by mkurz** [comment]
Update to `1.3.3`.

**Comment by mkurz** [comment]
Also upgrade Scala to 2.12.10

**Comment by mkurz** [comment]
Also upgraded to latest `sbt-coursier`.
However Travis is not really happy...
Maybe someone can clean Travis' cache and try again. Otherwise I am done for now.

**Comment by mkurz** [comment]
Happens locally here as well, so Travis not to blame.

**Comment by djspiewak** [comment]
Ah I think the problem is that Coursier is now baked into sbt, so we should probably just remove the plugin.

Also 👋 sorry for my silence on this. Been really busy lately. I'll try to loop back to this shortly!

**Comment by mkurz** [comment]
@djspiewak Plugin removed.

**Comment by djspiewak** [comment]
Thank you so much for your work on this, @mkurz! Sorry again for the intensely long delay.

**Pull request merged**
